server {
    listen 127.0.0.1:8080;
    client_max_body_size 10485760;

    location / {
        root resources/www;
        index index.html;
        allowed_methods GET;
        autoindex off;
    }

    location /upload {
        root resources/upload;
        allowed_methods GET POST DELETE;
        autoindex on;
        upload_store resources/upload;
    }

    location /cgi-bin {
        root resources/cgi-bin;
        allowed_methods GET POST;
        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .py /usr/bin/python3;
    }

    location /redirect {
        return 302 /;
    }
}

server {
    listen 127.0.0.1:9090;
    client_max_body_size 1048576;

    location / {
        root resources/cgi-bin;
        allowed_methods GET;
        autoindex on;
    }
}
