# ===================================================================
# Webserv - Default Config File
# ===================================================================

# First virtual server: port 8080
server {
    listen 127.0.0.1:8080;
#listen 127.0.0.1:8080; # this should fail (duplicate listen directive)
#listen 300.0.0.1:8080; # this should fail (invalid IP address and duplicate)

    client_max_body_size 10485760;  # 10 MiB

# error_page 404 /home/viodid/Documents/42/webserv/resources/404.html; # check file exists and is readable
# error_page 500 /home/viodid/Documents/42/webserv/resources/500.html;

    location / {
        root /home/viodid/Documents/42/webserv/resources/www/portfolio; # check path exists and is readable
        index index.html;
        allowed_methods GET;
        autoindex off;
    }

    location /upload {
        root /var/www/html/upload;
        allowed_methods GET POST DELETE;
        autoindex on;
        upload_store /var/www/html/upload; # check path exists and is writable
    }

    location /cgi-bin {
        root /var/www/html/cgi-bin;
        allowed_methods GET POST;
        cgi_pass .php /usr/bin/php-cgi; # check binary exists and is executable
        cgi_pass .py /usr/bin/python3;
    }

    location /redirect {
        return 302 /;
    }
}

# Second virtual server: port 9090
server {
    listen 0.0.0.0:9090;
    client_max_body_size 1048576;   # 1 MiB

    error_page 404 /var/www/alt/404.html;

    location / {
        root /home/viodid/Documents/42/webserv/resources/www/static_test;
#index index.html; # check index.html exists at the given path and is readable
        allowed_methods GET;
        autoindex on;
    }
}
